#!/bin/sh

if [ "$1" = "" ]; then
	echo PVR-INIT: Please use start, stop, or restart.
	exit 1
fi

if [ "$1" = "stop" -o  "$1" = "restart" ]; then
	echo Stopping PVR
	rmmod bufferclass_ti 2>/dev/null
	rmmod omaplfb 2>/dev/null
	rmmod pvrsrvkm 2>/dev/null
fi

if [ "$1" = "stop" ]; then
	exit 0
fi

echo Starting PVR
modprobe omaplfb
modprobe bufferclass_ti

pvr_maj=`grep "pvrsrvkm$" /proc/devices | cut -b1,2,3`
bc_maj=`grep "bc" /proc/devices | cut -b1,2,3`

if [ -e /dev/pvrsrvkm ] ; then 
	rm -f /dev/pvrsrvkm
fi

#remove with 06
if [ -e /dev/bc_cat ] ; then 
	rm -f /dev/bc_cat
fi

mknod /dev/pvrsrvkm c $pvr_maj 0 
chmod 666 /dev/pvrsrvkm

#remove with 06
mknod /dev/bc_cat c $bc_maj 0
chmod 666 /dev/bc_cat

touch /etc/powervr-esrev

SAVED_ESREVISION="$(cat /etc/powervr-esrev)"
ES_REVISION="$(cat /proc/cpuinfo | grep "CPU revision" | awk -F: '{print $2}')"

if [ "${ES_REVISION}" != "${SAVED_ESREVISION}" ] ; then
	echo -n "Starting SGX fixup for"
	if [ "${ES_REVISION}" = " 3" ] ; then
	echo " ES3.x"
	cp -a /usr/lib/ES3.0/* /usr/lib
	cp -a /usr/bin/ES3.0/* /usr/bin	
	else
	echo " ES2.x"
	cp -a /usr/lib/ES2.0/* /usr/lib
	cp -a /usr/bin/ES2.0/* /usr/bin	
	fi
	
	echo "${ES_REVISION}" > /etc/powervr-esrev
fi

/usr/bin/pvrsrvinit

